version: "3.8"
services:
    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: main
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        environment: 
            - PORT=8000
            - DATABASE_URL=mysql+pymysql://root:password@mysql:3306/main
        ports:
            - "8001:8000"
        depends_on: 
            - mysql